export const HTMLTagNamesToString = {
  DIV: 'Div',
  H1: 'Heading 1',
  H2: 'Heading 2',
  H3: 'Heading 3',
  H4: 'Heading 4',
  H5: 'Heading 5',
  H6: 'Heading 6',
  P: 'Paragraph',
  SPAN: 'Span',
  UL: 'Unordered List',
  LI: 'List Item',
  IMG: 'Image',
  STRONG: 'Strong Text',
  EM: 'Emphasised Text',
  I: 'Icon',
  A: 'Link',
  INPUT: 'Input',
  BLOCKQUOTE: 'Quote',
  FIGCAPTION: 'Caption',
  BUTTON: 'Button'
};
