import keyMirror from 'react/lib/keyMirror';

export default keyMirror({
  GET_BUILDER_CONFIGURATION: Symbol('GET_BUILDER_CONFIGURATION'),
  RECEIVE_BUILDER_CONFIGURATION: Symbol('RECEIVE_BUILDER_CONFIGURATION'),

  GET_LOCALIZATION: Symbol('GET_LOCALIZATION'),
  PROCCESS_LOCALIZATION: Symbol('PROCCESS_LOCALIZATION'),

  PROCESS_TEMPLATE_SELECTION: Symbol('PROCESS_TEMPLATE_SELECTION')
});